//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capicua.Patrones.Ejemplo.Factory01.CurrentDateTimeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrentDateTimeServiceReference.ICurrentDateTimeService")]
    public interface ICurrentDateTimeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentDateTimeService/Obtain", ReplyAction="http://tempuri.org/ICurrentDateTimeService/ObtainResponse")]
        System.DateTime Obtain();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrentDateTimeServiceChannel : Capicua.Patrones.Ejemplo.Factory01.CurrentDateTimeServiceReference.ICurrentDateTimeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrentDateTimeServiceClient : System.ServiceModel.ClientBase<Capicua.Patrones.Ejemplo.Factory01.CurrentDateTimeServiceReference.ICurrentDateTimeService>, Capicua.Patrones.Ejemplo.Factory01.CurrentDateTimeServiceReference.ICurrentDateTimeService {
        
        public CurrentDateTimeServiceClient() {
        }
        
        public CurrentDateTimeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrentDateTimeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrentDateTimeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrentDateTimeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime Obtain() {
            return base.Channel.Obtain();
        }
    }
}
