//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capicua.Patrones.Ejemplo.Adapter01.FechaActualServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FechaActualServiceReference.IFechaActualService")]
    public interface IFechaActualService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFechaActualService/Obtener", ReplyAction="http://tempuri.org/IFechaActualService/ObtenerResponse")]
        System.DateTime Obtener();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFechaActualServiceChannel : Capicua.Patrones.Ejemplo.Adapter01.FechaActualServiceReference.IFechaActualService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FechaActualServiceClient : System.ServiceModel.ClientBase<Capicua.Patrones.Ejemplo.Adapter01.FechaActualServiceReference.IFechaActualService>, Capicua.Patrones.Ejemplo.Adapter01.FechaActualServiceReference.IFechaActualService {
        
        public FechaActualServiceClient() {
        }
        
        public FechaActualServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FechaActualServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FechaActualServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FechaActualServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime Obtener() {
            return base.Channel.Obtener();
        }
    }
}
